# Generated by Django 3.2.14 on 2022-07-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0009_userprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='profile_picture',
        ),
    ]
